version: "3.8"
services:
  backend:
    image: rpicpt-backend
    container_name: rpicpt-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    privileged: true
    stop_signal: SIGINT
    restart: unless-stopped
    # environment:
    #   - OPENCV_LOG_LEVEL=DEBUG
    #   - OPENCV_VIDEOIO_DEBUG=1
