version: "3.8"
services:
  sitl:
    image: rpicpt-backend
    container_name: rpicpt-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    privileged: true
